# Generated by Django 2.1.5 on 2022-03-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UID',
            field=models.IntegerField(default=0),
        ),
    ]
