# Generated by Django 2.1.5 on 2022-03-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UID',
        ),
    ]
