# Generated by Django 2.1.5 on 2022-03-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Ticker', models.TextField()),
                ('Percentage', models.FloatField()),
            ],
        ),
    ]
