# Generated by Django 2.1.5 on 2022-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='iOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
